### ISSUE TITLE
How could I get the information from the pouchdb

### ISSUE THREAD

**Issue by Avijeetmishra** [sadick254/vuepouch#1]
I could only add,update or delete the record. How could I retrieve the information from PouchDb. Is there any other method like db.get() to retrieve the information from PouchDb.

Thanks for the nice code!!

**Comment by sadick254** [comment]
Hi @Avijeetmishra currently there is no such method for getting information from pouchdb. Am currently rewriting the vuepouch library to address some of the concerns. Thanks for checking out vuepouch. Your contribution is welcomed.

**Comment by Avijeetmishra** [comment]
Cool. Thanks for the reply!!!

**Comment by sadick254** [comment]
@Avijeetmishra  I have updated the code. You can now get a similar functionality described above but through computed properties. Please check the projects readme file.

**Comment by Avijeetmishra** [comment]
Thanks for the effort!!
