### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Jinjinov** [sadick254/vuepouch#2]
i am a javascript noob, but i think that your Usage code has 2 mistakes:
`localdb: "uber",` should be `localDB: "uber",`
and
`computed () {` should be `computed: {`
correct me if i am wrong
but i still can't get your example to work, because i don't know how your database looks like.
i would be really grateful if you could provide a JSON file with `drivers` and `passengers` object
thank you!

**Comment by sadick254** [comment]
Hi @Jinjinov Thanks for pointing that error in the usage code. As for what the database looks like, you can save any valid javascript object. Are you getting any errors?

**Comment by Jinjinov** [comment]
it was my mistake (i use C# for 15 years, but i never used javascript) - i have all my data in YAML and i changed YAML to JSON and saved it in CouchDB with Fauxton, but i couldn't load it with "vuepouch". 

Fauxton generates `"_id":"some guid"` and `"_rev":"some guid"` so i changed it to `"_id":"drivers"` but it didn't work - this was my mistake.

today i read your code and i saw `data['doctype'] = docName` in the `function put(docName, data)` and i added `"doctype":` to my data that i imported from YAML and now it works! thank you!
